.TH owo 1  "June 26, 2018" "version 1.0.0" "USER COMMANDS"
.SH NAME
owo \- make use of whats-th.is file upload and link shortening services
.SH SYNOPSIS
.B owo
[option...] [file...]
.SH DESCRIPTION
This little tool helps you upload files and shorten links via awau.moe.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
display a short help text
.TP
\fB\-v\fR, \fB\-\-verbose\fR
enable verbose logging
.TP
\fB\-\-version\fR
show version and copyright information
.TP
\fB\-\-dry-run\fR
do not actually upload
.TP
\fB\-\-no\-colors\fR
disable ascii coloring
.TP
\fB\-l\fR, \fB\-\-shorten\fR link
shorten a link passed as string 'link'
.TP
\fB\-u\fR, \fB\-\-upload\fR file
upload a file passed as string 'file', this option can be repeated
.TP
\fB\-s\fR, \fB\-\-screenshot\fR
select and screenshot
.TP
\fB\-r\fR, \fB\-\-record\fR
record screen
.TP
\fB\-\-fullscreen\fR
enable fullscreen screenshots, use with -s or -r
.TP
\fB\-\-key\fR key
key to authorize with, passed as string 'key'
.TP
\fB\-\-domain\fR domain
domain to use for resulting uploads, passed as string 'domain'
.TP
\fB\-\-no\-cursor\fR
disable cursor in screenshots
.TP
\fB\-\-screenshots\-dir\fR dir
screenshots directory, empty to disable, will be created if doesn't exist, passed as string 'dir'
.TP
\fB\-\-record\-format\fR
recorder format

.SH EXAMPLES
.TP
Upload file:
.B owo
\-u test.bin
.PP
.TP
Shorten link:
.B owo
\-l 'https://duckduckgo.com'
.PP
.SH EXIT STATUS
owo returns a zero exit status if it succeeds in all given tasks.
Non zero is returned in case of failure, as script uses set -e.
.SH AUTHOR
OwO developers (devs (at) whats-th.is)
.SH SEE ALSO
curl(1)
maim(1)
slop(1)
